const ACTIONS = {
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
  SET_SEARCHTITLE: "SET_SEARCHTITLE",
  SET_ORDER: "SET_ORDER",
  SET_SORT: "SET_SORT",
  SET_STATUS: "SET_STATUS",
  SET_BUTTONDATA: "SET_BUTTONDATA",
};

export default ACTIONS;
